version: '3.1'

services:
### Workspace Utilities Container ###########################
  workspace:
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ./varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ~/.ssh:/home/laradock/.ssh
    network_mode: "host"

### PHP-FPM Container #######################################
  php-fpm:
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ./varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    network_mode: "host"

### SSL ##################################
  ssl:
    volumes:
      - ./ssl:/certs

### Nginx Server Container ##################################
  nginx:
    volumes:
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ./varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_CONF_M2_PATH}:/etc/nginx/conf_m2
    network_mode: "host"

### Apache Server ########################################
#  apache2:
#    volumes:
#      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
#      - ./xhgui:${XHGUI_CODE_PATH_CONTAINER}
#      - ./varnish/health_check.php:${DEFAULT_PATH}/health_check.php
#      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
#      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
#    network_mode: "host"

#### Postfix Server Container ################################
  postfix:
    network_mode: "host"

### Redis Container #########################################
  redis:
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    network_mode: "host"

### Memcached ############################################
  memcached:
    volumes:
      - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
    network_mode: "host"

### Percona ################################################
#  percona:
#    volumes:
#      - ${DATA_PATH_HOST}/percona:/var/lib/mysql
#      - ${PERCONA_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
#    networks_mode: "host"

### RabbitMQ #############################################
  rabbitmq:
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
    network_mode: "host"

### Varnish ##########################################
  proxy:
    network_mode: "host"

### Blackfire ########################################
#  blackfire:
#    networks_mode: "host"

### MongoDB ##############################################
  mongo:
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
    network_mode: "host"

### ElasticSearch ########################################
  elasticsearch:
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    network_mode: "host"
