version: '2'

services:
### Workspace Utilities Container ###########################
  workspace:
    extends:
      file: ../../common/docker-compose.yml
      service: workspace
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/workspace/ext-xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini
      - ./config/workspace/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
      - ./config/workspace/ext-tideways_xhprof.ini:/etc/php/${PHP_VERSION}/cli/conf.d/tideways_xhprof.ini
      - ./volumes/shared/log/magento/:/var/www/app/var/log
      - ./volumes/composer:/home/laradock/.composer
      - ./volumes/ssh:/home/laradock/.ssh
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"

### PHP-FPM Container #######################################
  php-fpm:
    extends:
      file: ../../common/docker-compose.yml
      service: php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./config/php-fpm/ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/php-fpm/ext-tideways_xhprof.ini:/usr/local/etc/php/conf.d/tideways_xhprof.ini
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ./volumes/shared/log/magento/:/var/www/app/var/log
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"

### SSL ##################################
  ssl:
    extends:
      file: ../../common/docker-compose.yml
      service: ssl
    volumes:
      - ./volumes/ssl/certs:/certs

### Nginx Server Container ##################################
  nginx:
    extends:
      file: ../../common/docker-compose.yml
      service: nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf_m2/:/etc/nginx/conf_m2
      - ./volumes/ssl/certs/:/etc/nginx/ssl
      - ./volumes/shared/log/nginx/:/var/log/nginx
    depends_on:
      - php-fpm
      - ssl

### Varnish ##########################################
  varnish:
    extends:
      file: ../../common/docker-compose.yml
      service: varnish
    depends_on:
      - php-fpm

### Redis Container #########################################
  redis:
    extends:
      file: ../../common/docker-compose.yml
      service: redis
#    volumes:
#      - ${DATA_PATH_HOST}/redis:/data

#### Postfix Server Container ################################
  postfix:
    extends:
      file: ../../common/docker-compose.yml
      service: postfix
    volumes:
      - ./volumes/postfix/Maildir:/root/Maildir

### Mailhog Container #####################################
  mailhog:
    extends:
      file: ../../common/docker-compose.yml
      service: mailhog
    volumes:
      - ./volumes/email:/mnt/storage

### ElasticSearch ########################################
  elasticsearch:
    build:
      context: ./config/elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
        - INSTALL_PHONETIC=${ELASTICSEARCH_INSTALL_PHONETIC}
        - INSTALL_ICU=${ELASTICSEARCH_INSTALL_ICU}
    environment:
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

### Kibana ##############################################
  kibana:
    build:
      context: ./config/kibana
      args:
        - ELK_VERSION=${ELK_VERSION}
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    depends_on:
      - elasticsearch

### RabbitMQ #############################################
  rabbitmq:
    extends:
      file: ../../common/docker-compose.yml
      service: rabbitmq
#    volumes:
#      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
    depends_on:
      - php-fpm

### MongoDB ##############################################
  mongo:
    extends:
      file: ../../common/docker-compose.yml
      service: mongo
#    volumes:
#      - ${DATA_PATH_HOST}/mongo:/data/db

### Logrotate Container ####################################
  logrotate:
    extends:
      file: ../../common/docker-compose.yml
      service: logrotate
    volumes:
      - ./config/logrotate/logrotate.conf:/etc/logrotate.conf
      - ./volumes/shared/log:/log

