version: '2'

services:
### Workspace Utilities Container ###########################
  workspace:
    extends:
      file: ../../common/docker-compose.yml
      service: workspace
    volumes:
      - applications-sync:${APP_CODE_PATH_CONTAINER}:nocopy # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/workspace/ext-xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini:delegated
      - ./config/workspace/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini:delegated
      - ./config/workspace/ext-xhprof.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xhprof.ini:delegated
      - ./volumes/composer:/home/laradock/.composer:delegated
      - ./volumes/ssh:/home/laradock/.ssh:delegated

### PHP-FPM Container #######################################
  php-fpm:
    extends:
      file: ../../common/docker-compose.yml
      service: php-fpm
    volumes:
      - applications-sync:${APP_CODE_PATH_CONTAINER}:nocopy # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini:delegated
      - ./config/php-fpm/ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
      - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:delegated
      - ./config/php-fpm/ext-xhprof.ini:/usr/local/etc/php/conf.d/xhprof.ini:delegated
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php:delegated

### XHGUI Container #######################################
  xhgui:
    extends:
      file: ../../common/docker-compose.yml
      service: xhgui
    volumes:
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}:delegated

### SSL ##################################
  ssl:
    extends:
      file: ../../common/docker-compose.yml
      service: ssl
    volumes:
      - ./volumes/ssl/certs:/certs

### Nginx Server Container ##################################
  nginx:
    extends:
      file: ../../common/docker-compose.yml
      service: nginx
    volumes:
      - applications-sync:${APP_CODE_PATH_CONTAINER}:nocopy # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}:delegated
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php:delegated
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf_m2/:/etc/nginx/conf_m2
      - ./volumes/ssl/certs/:/etc/nginx/ssl
    depends_on:
      - php-fpm
      - ssl

### Varnish ##########################################
  varnish:
    extends:
      file: ../../common/docker-compose.yml
      service: varnish
    depends_on:
      - php-fpm

### Redis Container #########################################
  redis:
    extends:
      file: ../../common/docker-compose.yml
      service: redis
#    volumes:
#      - ./volumes/redis:/data:delegated

#### Postfix Server Container ################################
  postfix:
    extends:
      file: ../../common/docker-compose.yml
      service: postfix
    volumes:
      - ./volumes/postfix/Maildir:/root/Maildir

### Mailpit Container #####################################
  mailpit:
    extends:
      file: ../../common/docker-compose.yml
      service: mailpit
    volumes:
      - ./volumes/email:/data

### RabbitMQ #############################################
  rabbitmq:
    extends:
      file: ../../common/docker-compose.yml
      service: rabbitmq
#    volumes:
#      - ./volumes/rabbitmq:/var/lib/rabbitmq:delegated

### MongoDB ##############################################
  mongo:
    extends:
      file: ../../common/docker-compose.yml
      service: rabbitmq
#    volumes:
#      - ./volumes/mongo:/data/db:delegated

### Logrotate Container ####################################
  logrotate:
    extends:
      file: ../../common/docker-compose.yml
      service: logrotate
    volumes:
      - ./config/logrotate/logrotate.conf:/etc/logrotate.conf
      - ./volumes/shared/log:/log

volumes:
  applications-sync:
    external:
      name: "${SYNC_NAME}-docker-sync"
