version: '2'

services:
### Workspace Utilities Container ###########################
  workspace:
    extends:
      file: ../../common/docker-compose.yml
      service: workspace
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/workspace/ext-xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/20-xdebug.ini
      - ./config/workspace/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
      - ./config/workspace/ext-tideways_xhprof.ini:/etc/php/${PHP_VERSION}/cli/conf.d/tideways_xhprof.ini
      - ./volumes/composer:/home/laradock/.composer
      - ./volumes/ssh:/home/laradock/.ssh

### PHP-FPM Container #######################################
  php-fpm:
    extends:
      file: ../../common/docker-compose.yml
      service: php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ./config/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./config/php-fpm/ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php-fpm/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
      - ./config/php-fpm/ext-tideways_xhprof.ini:/usr/local/etc/php/conf.d/tideways_xhprof.ini
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php

### SSL ##################################
  ssl:
    extends:
      file: ../../common/docker-compose.yml
      service: ssl
    volumes:
      - ./volumes/ssl/certs:/certs

### Nginx Server Container ##################################
  nginx:
    extends:
      file: ../../common/docker-compose.yml
      service: nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER} # will be mounted on to the value of APP_CODE_PATH_CONTAINER
      - ../../common/xhgui:${XHGUI_CODE_PATH_CONTAINER}
      - ../../common/config/varnish/health_check.php:${DEFAULT_PATH}/health_check.php
      - ./config/nginx/sites/:/etc/nginx/sites-available
      - ./config/nginx/conf_m2/:/etc/nginx/conf_m2
      - ./volumes/ssl/certs/:/etc/nginx/ssl
    depends_on:
      - php-fpm
      - ssl

### Varnish ##########################################
  varnish:
    extends:
      file: ../../common/docker-compose.yml
      service: varnish
    depends_on:
      - php-fpm

### Redis Container #########################################
  redis:
    extends:
      file: ../../common/docker-compose.yml
      service: redis
#    volumes:
#      - ${DATA_PATH_HOST}/redis:/data

#### Postfix Server Container ################################
  postfix:
    extends:
      file: ../../common/docker-compose.yml
      service: postfix
    volumes:
      - ./volumes/postfix/Maildir:/root/Maildir

### Mailhog Container #####################################
  mailhog:
    extends:
      file: ../../common/docker-compose.yml
      service: mailhog
    volumes:
      - ./volumes/email:/mnt/storage

### RabbitMQ #############################################
  rabbitmq:
    extends:
      file: ../../common/docker-compose.yml
      service: rabbitmq
#    volumes:
#      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq

### MongoDB ##############################################
  mongo:
    extends:
      file: ../../common/docker-compose.yml
      service: mongo
#    volumes:
#      - ${DATA_PATH_HOST}/mongo:/data/db

### Logrotate Container ####################################
  logrotate:
    extends:
      file: ../../common/docker-compose.yml
      service: logrotate
    volumes:
      - ./config/logrotate/logrotate.conf:/etc/logrotate.conf
      - ./volumes/shared/log:/log

